FROM python:3.12.0-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Default values for environment variables
ENV PORT=8000
ENV REDIS_HOST=feed-redis
ENV REDIS_PORT=6379

EXPOSE 8000

CMD uvicorn app:app --host 0.0.0.0 --port $PORT